# edi_seed.py
# Comando para ejecutar: python manage.py shell < edi_seed.py

from Form.models import EDIQuestion

def create_edi_questions():
    """Carga todas las preguntas EDI en la base de datos"""
    
    questions_data = [
        # ==================== GRUPO 01 (1 mes - 1m29d) ====================
        # Motriz Gruesa
        {"age_group": "01", "code": "01_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando su bebé está acostado boca abajo, ¿puede voltear su cabeza para los dos lados?",
         "is_critical": True, "order": 1},
        {"age_group": "01", "code": "01_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando desviste a su bebé, ¿patea y mueve los brazos?",
         "is_critical": False, "order": 2},
        
        # Motriz Fina
        {"age_group": "01", "code": "01_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Su bebé mantiene las manos cerradas la mayor parte del tiempo?",
         "is_critical": False, "order": 3},
        {"age_group": "01", "code": "01_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "Cuando le da en la mano una sonaja a su bebé, ¿la retiene durante al menos 3 segundos?",
         "is_critical": True, "order": 4},
        
        # Lenguaje
        {"age_group": "01", "code": "01_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Su bebé se tranquiliza cuando escucha su voz?",
         "is_critical": False, "order": 5},
        {"age_group": "01", "code": "01_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Hace algún ruido con la boca, llora cuando está incómodo o quiere comer?",
         "is_critical": False, "order": 6},
        
        # Social
        {"age_group": "01", "code": "01_S_1", "question_type": "AREA", "area": "social",
         "text": "Cuando llora, ¿se tranquiliza al hablarle o levantarlo?",
         "is_critical": False, "order": 7},
        {"age_group": "01", "code": "01_S_2", "question_type": "AREA", "area": "social",
         "text": "Cuando usted está frente a su bebé, ¿sigue con la mirada sus movimientos?",
         "is_critical": True, "order": 8},
        
        # Exploración Neurológica
        {"age_group": "01", "code": "01_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 9},
        {"age_group": "01", "code": "01_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 10},
        {"age_group": "01", "code": "01_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 11},
        
        # Señales de Alerta
        {"age_group": "01", "code": "01_ALE_1", "question_type": "ALARM", "area": None,
         "text": "Al evaluar el tono muscular de su niño, ¿lo siente totalmente flácido o presenta rigidez en sus extremidades?",
         "is_critical": True, "order": 12},
        {"age_group": "01", "code": "01_ALE_2", "question_type": "ALARM", "area": None,
         "text": "En la evaluación de los reflejos de Moro, prensión palmar y plantar, ¿falta alguno de estos 3 reflejos?",
         "is_critical": True, "order": 13},
        {"age_group": "01", "code": "01_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Su hijo tiene problemas para comer: se atraganta, se pone morado o presenta problemas para succionar?",
         "is_critical": False, "order": 14},
        {"age_group": "01", "code": "01_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿Considera que el desarrollo de su niño es inadecuado?",
         "is_critical": False, "order": 15},
        
        # Factores de Riesgo Biológico
        {"age_group": "01", "code": "01_FRB_1", "question_type": "BIO", "area": None,
         "text": "Asistencia a dos o menos consultas prenatales.",
         "is_critical": False, "order": 16},
        {"age_group": "01", "code": "01_FRB_2", "question_type": "BIO", "area": None,
         "text": "Presencia de sangrados, infecciones de vías urinarias o cervicovaginitis, presión alta o enfermedades sistémicas durante el embarazo.",
         "is_critical": False, "order": 17},
        {"age_group": "01", "code": "01_FRB_3", "question_type": "BIO", "area": None,
         "text": "Gestación menor a 34 semanas.",
         "is_critical": False, "order": 18},
        {"age_group": "01", "code": "01_FRB_4", "question_type": "BIO", "area": None,
         "text": "Peso de su niño al nacer de 1500 g o menos.",
         "is_critical": False, "order": 19},
        {"age_group": "01", "code": "01_FRB_5", "question_type": "BIO", "area": None,
         "text": "Retardo en la respiración o circular de cordón a cuello durante el parto o cesárea.",
         "is_critical": False, "order": 20},
        {"age_group": "01", "code": "01_FRB_6", "question_type": "BIO", "area": None,
         "text": "Hospitalización de su niño en la Unidad de Cuidados Intensivos Neonatales (UCIN) al nacimiento o antes del primer mes de vida con una duración mayor a 4 días.",
         "is_critical": False, "order": 21},
        {"age_group": "01", "code": "01_FRB_7", "question_type": "BIO", "area": None,
         "text": "Madre menor a 16 años al momento del parto.",
         "is_critical": False, "order": 22},

        # ==================== GRUPO 02 (2 meses - 2m29d) ====================
        # Motriz Gruesa
        {"age_group": "02", "code": "02_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando acuesta a su bebé boca abajo, ¿levanta su cabeza durante al menos 3 segundos?",
         "is_critical": True, "order": 1},
        {"age_group": "02", "code": "02_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando carga a su bebé, ¿logra sostener la cabeza sin que se le vaya bruscamente hacia atrás o hacia alguno de los lados?",
         "is_critical": True, "order": 2},
        
        # Motriz Fina
        {"age_group": "02", "code": "02_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede seguir con la vista el movimiento de objetos de colores vivos?",
         "is_critical": True, "order": 3},
        {"age_group": "02", "code": "02_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Se lleva la mano a la boca?",
         "is_critical": True, "order": 4},
        
        # Lenguaje
        {"age_group": "02", "code": "02_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "Cuando su bebé oye un ruido, ¿voltea hacia la fuente de sonido, estando ésta fuera de su campo visual?",
         "is_critical": True, "order": 5},
        {"age_group": "02", "code": "02_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Hace sonidos como \"a\", \"e\", \"u\"?",
         "is_critical": False, "order": 6},
        
        # Social
        {"age_group": "02", "code": "02_S_1", "question_type": "AREA", "area": "social",
         "text": "¿Hace sonidos con la boca cuando le hablan?",
         "is_critical": False, "order": 7},
        {"age_group": "02", "code": "02_S_2", "question_type": "AREA", "area": "social",
         "text": "¿Reconoce los rostros que le son familiares y sonríe?",
         "is_critical": False, "order": 8},
        
        # Exploración Neurológica
        {"age_group": "02", "code": "02_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 9},
        {"age_group": "02", "code": "02_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 10},
        {"age_group": "02", "code": "02_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 11},
        
        # Señales de Alarma
        {"age_group": "02", "code": "02_ALE_1", "question_type": "ALARM", "area": None,
         "text": "Al evaluar el tono muscular de su niño, ¿lo siente totalmente flácido o presenta rigidez en sus extremidades?",
         "is_critical": True, "order": 12},
        {"age_group": "02", "code": "02_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿El reflejo de Moro está ausente o es asimétrico?",
         "is_critical": True, "order": 13},
        {"age_group": "02", "code": "02_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Frecuentemente se encuentra aletargado y no muestra interés por lo que sucede a su alrededor?, ¿cuesta trabajo mantenerlo despierto?",
         "is_critical": False, "order": 14},
        {"age_group": "02", "code": "02_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿Están las manos de su niño permanentemente empuñadas con el pulgar adentro?",
         "is_critical": True, "order": 15},
        {"age_group": "02", "code": "02_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿Está el niño frecuentemente irritable y cuesta trabajo tranquilizarlo a pesar de haber satisfecho sus necesidades y de forma más notoria que otros niños de su edad?",
         "is_critical": False, "order": 16},
        {"age_group": "02", "code": "02_ALE_6", "question_type": "ALARM", "area": None,
         "text": "¿Su hijo tiene problemas para comer: se atraganta, se pone morado o presenta problemas para succionar?",
         "is_critical": False, "order": 17},
        {"age_group": "02", "code": "02_ALE_7", "question_type": "ALARM", "area": None,
         "text": "¿Considera que el desarrollo de su niño es inadecuado?",
         "is_critical": False, "order": 18},
        
        # FRB (iguales al grupo 01)
        {"age_group": "02", "code": "02_FRB_1", "question_type": "BIO", "area": None,
         "text": "Asistencia a dos o menos consultas prenatales.",
         "is_critical": False, "order": 19},
        {"age_group": "02", "code": "02_FRB_2", "question_type": "BIO", "area": None,
         "text": "Presencia de sangrados, infecciones de vías urinarias o cervicovaginitis, presión alta o enfermedades sistémicas durante el embarazo.",
         "is_critical": False, "order": 20},
        {"age_group": "02", "code": "02_FRB_3", "question_type": "BIO", "area": None,
         "text": "Gestación menor a 34 semanas.",
         "is_critical": False, "order": 21},
        {"age_group": "02", "code": "02_FRB_4", "question_type": "BIO", "area": None,
         "text": "Peso de su niño al nacer de 1500 g o menos.",
         "is_critical": False, "order": 22},
        {"age_group": "02", "code": "02_FRB_5", "question_type": "BIO", "area": None,
         "text": "Retardo en la respiración o circular de cordón a cuello durante el parto o cesárea.",
         "is_critical": False, "order": 23},
        {"age_group": "02", "code": "02_FRB_6", "question_type": "BIO", "area": None,
         "text": "Hospitalización de su niño en la Unidad de Cuidados Intensivos Neonatales (UCIN) al nacimiento o antes del primer mes de vida con una duración mayor a 4 días.",
         "is_critical": False, "order": 24},
        {"age_group": "02", "code": "02_FRB_7", "question_type": "BIO", "area": None,
         "text": "Madre menor a 16 años al momento del parto.",
         "is_critical": False, "order": 25},

        # ==================== GRUPO 03 (3 meses - 3m29d) ====================
        # Motriz Gruesa
        {"age_group": "03", "code": "03_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando su bebé está boca abajo y apoyado en sus antebrazos, ¿logra sostener la cabeza al menos 3 segundos?",
         "is_critical": True, "order": 1},
        {"age_group": "03", "code": "03_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando sienta a su bebé, ¿ha observado si logra sostener la cabeza sin que se le vaya bruscamente hacia enfrente, atrás o hacia alguno de los lados?",
         "is_critical": True, "order": 2},
        
        # Motriz Fina
        {"age_group": "03", "code": "03_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Se ha fijado si su bebé observa sus manos durante al menos 3 segundos mientras las está moviendo?",
         "is_critical": False, "order": 3},
        {"age_group": "03", "code": "03_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Tiene su bebé las manos abiertas la mayor parte del tiempo?",
         "is_critical": True, "order": 4},
        
        # Lenguaje
        {"age_group": "03", "code": "03_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "Cuando le hablan a su bebé, ¿hace sonidos con la boca o sonríe?",
         "is_critical": False, "order": 5},
        {"age_group": "03", "code": "03_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "Cuando balbucea, ¿pronuncia alguna consonante como \"agu\" o \"ga\"?",
         "is_critical": False, "order": 6},
        
        # Social
        {"age_group": "03", "code": "03_S_1", "question_type": "AREA", "area": "social",
         "text": "¿Es fácil que su bebé sonría?",
         "is_critical": False, "order": 7},
        {"age_group": "03", "code": "03_S_2", "question_type": "AREA", "area": "social",
         "text": "Cuando usted le habla al bebé fuera de su campo visual, ¿voltea la cabeza y trata de ubicar el origen de su voz?",
         "is_critical": True, "order": 8},
        
        # Exploración Neurológica
        {"age_group": "03", "code": "03_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 9},
        {"age_group": "03", "code": "03_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 10},
        {"age_group": "03", "code": "03_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 11},
        
        # Señales de Alarma
        {"age_group": "03", "code": "03_ALE_1", "question_type": "ALARM", "area": None,
         "text": "Al evaluar el tono muscular del niño, ¿lo siente totalmente flácido o presenta rigidez en sus extremidades?",
         "is_critical": True, "order": 12},
        {"age_group": "03", "code": "03_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿El reflejo de Moro está ausente o es asimétrico?",
         "is_critical": True, "order": 13},
        {"age_group": "03", "code": "03_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Cuándo lo sostiene por el tronco su cabeza cae bruscamente hacia enfrente, atrás o a los lados?",
         "is_critical": True, "order": 14},
        {"age_group": "03", "code": "03_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta seguir con la vista a las personas y a los objetos brillantes?",
         "is_critical": True, "order": 15},
        {"age_group": "03", "code": "03_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿Se mantiene serio o inexpresivo cuando la madre, padre o cuidador primario le sonríe?",
         "is_critical": False, "order": 16},
        {"age_group": "03", "code": "03_ALE_6", "question_type": "ALARM", "area": None,
         "text": "¿Considera que el desarrollo de su niño es inadecuado?",
         "is_critical": False, "order": 17},
        
        # FRB (iguales)
        {"age_group": "03", "code": "03_FRB_1", "question_type": "BIO", "area": None,
         "text": "Asistencia a dos o menos consultas prenatales.",
         "is_critical": False, "order": 18},
        {"age_group": "03", "code": "03_FRB_2", "question_type": "BIO", "area": None,
         "text": "Presencia de sangrados, infecciones de vías urinarias o cervicovaginitis, presión alta o enfermedades sistémicas durante el embarazo.",
         "is_critical": False, "order": 19},
        {"age_group": "03", "code": "03_FRB_3", "question_type": "BIO", "area": None,
         "text": "Gestación menor a 34 semanas.",
         "is_critical": False, "order": 20},
        {"age_group": "03", "code": "03_FRB_4", "question_type": "BIO", "area": None,
         "text": "Peso de su niño al nacer de 1500 g o menos.",
         "is_critical": False, "order": 21},
        {"age_group": "03", "code": "03_FRB_5", "question_type": "BIO", "area": None,
         "text": "Retardo en la respiración o circular de cordón a cuello durante el parto o cesárea.",
         "is_critical": False, "order": 22},
        {"age_group": "03", "code": "03_FRB_6", "question_type": "BIO", "area": None,
         "text": "Hospitalización de su niño en la Unidad de Cuidados Intensivos Neonatales (UCIN) al nacimiento o antes del primer mes de vida con una duración mayor a 4 días.",
         "is_critical": False, "order": 23},
        {"age_group": "03", "code": "03_FRB_7", "question_type": "BIO", "area": None,
         "text": "Madre menor a 16 años al momento del parto.",
         "is_critical": False, "order": 24},

        # ==================== GRUPO 04 (4 meses - 4m29d) ====================
        # Motriz Gruesa
        {"age_group": "04", "code": "04_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando su bebé está sentado y lo sostiene suavemente de la espalda, ¿mantiene su cabeza, sin dejarla caer hacia ningún lado por lo menos 1 minuto?",
         "is_critical": True, "order": 1},
        {"age_group": "04", "code": "04_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando su bebé está acostado boca arriba, ¿se voltea hacia los lados?",
         "is_critical": True, "order": 2},
        
        # Motriz Fina
        {"age_group": "04", "code": "04_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Extiende su bebé alguno de sus brazos para tratar de tomar un objeto que está a su alcance?",
         "is_critical": True, "order": 3},
        {"age_group": "04", "code": "04_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede mantener en la mano un objeto al menos 10 segundos?",
         "is_critical": True, "order": 4},
        
        # Lenguaje
        {"age_group": "04", "code": "04_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Balbucea o grita para llamar su atención?",
         "is_critical": False, "order": 5},
        {"age_group": "04", "code": "04_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Emite sonidos como \"le\", \"be\", \"pa\", \"gu\"?",
         "is_critical": False, "order": 6},
        
        # Social
        {"age_group": "04", "code": "04_S_1", "question_type": "AREA", "area": "social",
         "text": "Piensa usted que cuando su bebé ve su pecho o la leche, ¿sabe que en poco tiempo le va a dar de comer?",
         "is_critical": False, "order": 7},
        {"age_group": "04", "code": "04_S_2", "question_type": "AREA", "area": "social",
         "text": "¿Le gusta jugar con otras personas y llora cuando dejan de jugar con él?",
         "is_critical": False, "order": 8},
        
        # Exploración Neurológica
        {"age_group": "04", "code": "04_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 9},
        {"age_group": "04", "code": "04_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 10},
        {"age_group": "04", "code": "04_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 11},
        
        # Señales de Alarma
        {"age_group": "04", "code": "04_ALE_1", "question_type": "ALARM", "area": None,
         "text": "¿El reflejo de Moro está ausente o es asimétrico?",
         "is_critical": True, "order": 12},
        {"age_group": "04", "code": "04_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿Cuándo lo sostiene del tronco su cabeza cae bruscamente hacia enfrente, atrás o a los lados?",
         "is_critical": True, "order": 13},
        {"age_group": "04", "code": "04_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Hay asimetría en los movimientos de las manos?",
         "is_critical": True, "order": 14},
        {"age_group": "04", "code": "04_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿Muestra indiferencia por los objetos?",
         "is_critical": True, "order": 15},
        {"age_group": "04", "code": "04_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿Persiste el reflejo de Galant o de encurvación?",
         "is_critical": True, "order": 16},
        {"age_group": "04", "code": "04_ALE_6", "question_type": "ALARM", "area": None,
         "text": "¿Considera que el desarrollo de su niño es inadecuado?",
         "is_critical": False, "order": 17},
        
        # FRB
        {"age_group": "04", "code": "04_FRB_1", "question_type": "BIO", "area": None,
         "text": "Asistencia a dos o menos consultas prenatales.",
         "is_critical": False, "order": 18},
        {"age_group": "04", "code": "04_FRB_2", "question_type": "BIO", "area": None,
         "text": "Presencia de sangrados, infecciones de vías urinarias o cervicovaginitis, presión alta o enfermedades sistémicas durante el embarazo.",
         "is_critical": False, "order": 19},
        {"age_group": "04", "code": "04_FRB_3", "question_type": "BIO", "area": None,
         "text": "Gestación menor a 34 semanas.",
         "is_critical": False, "order": 20},
        {"age_group": "04", "code": "04_FRB_4", "question_type": "BIO", "area": None,
         "text": "Peso de su niño al nacer de 1500 g o menos.",
         "is_critical": False, "order": 21},
        {"age_group": "04", "code": "04_FRB_5", "question_type": "BIO", "area": None,
         "text": "Retardo en la respiración o circular de cordón a cuello durante el parto o cesárea.",
         "is_critical": False, "order": 22},
        {"age_group": "04", "code": "04_FRB_6", "question_type": "BIO", "area": None,
         "text": "Hospitalización de su niño en la Unidad de Cuidados Intensivos Neonatales (UCIN) al nacimiento o antes del primer mes de vida con una duración mayor a 4 días.",
         "is_critical": False, "order": 23},
        {"age_group": "04", "code": "04_FRB_7", "question_type": "BIO", "area": None,
         "text": "Madre menor a 16 años al momento del parto.",
         "is_critical": False, "order": 24},

        # ==================== GRUPO 05-06 (5-6 meses) ====================
        # Motriz Gruesa
        {"age_group": "05-06", "code": "05-06_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando usted toma a su bebé de los brazos para sentarlo, ¿él le ayuda jalándose y elevando la cabeza?",
         "is_critical": True, "order": 1},
        {"age_group": "05-06", "code": "05-06_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando usted para a su bebé sobre una superficie plana, ¿aguanta su peso sobre las piernas?",
         "is_critical": True, "order": 2},
        
        # Motriz Fina
        {"age_group": "05-06", "code": "05-06_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "Cuando su bebé agarra algún objeto, ¿se lo pasa de una mano a otra?",
         "is_critical": True, "order": 3},
        {"age_group": "05-06", "code": "05-06_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "Cuando sienta a su bebé encima de usted, ¿intenta insistentemente agarrar un objeto cercano a él, aunque no pueda alcanzarlo?",
         "is_critical": True, "order": 4},
        
        # Lenguaje
        {"age_group": "05-06", "code": "05-06_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "Si llama a su bebé cuando él no lo puede ver, ¿mueve la cabeza hacia su voz?",
         "is_critical": True, "order": 5},
        {"age_group": "05-06", "code": "05-06_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "Si usted imita los sonidos que su bebé emite, ¿vuelve él a repetirlos?",
         "is_critical": False, "order": 6},
        
        # Social
        {"age_group": "05-06", "code": "05-06_S_1", "question_type": "AREA", "area": "social",
         "text": "¿Se pone intranquilo cuando una persona desconocida trata de cargarlo?",
         "is_critical": False, "order": 7},
        {"age_group": "05-06", "code": "05-06_S_2", "question_type": "AREA", "area": "social",
         "text": "Cuando usted se tapa la cabeza con una tela, ¿se ríe cuando usted se destapa?",
         "is_critical": True, "order": 8},
        
        # Exploración Neurológica
        {"age_group": "05-06", "code": "05-06_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 9},
        {"age_group": "05-06", "code": "05-06_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 10},
        {"age_group": "05-06", "code": "05-06_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 11},
        
        # Señales de Alarma
        {"age_group": "05-06", "code": "05-06_ALE_1", "question_type": "ALARM", "area": None,
         "text": "¿Hay asimetría en los movimientos de las manos?",
         "is_critical": True, "order": 12},
        {"age_group": "05-06", "code": "05-06_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿Persiste el reflejo de Galant o de encurvación?",
         "is_critical": True, "order": 13},
        {"age_group": "05-06", "code": "05-06_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Presenta desinterés por sus manos?",
         "is_critical": False, "order": 14},
        {"age_group": "05-06", "code": "05-06_ALE_4", "question_type": "ALARM", "area": None,
         "text": "Rara vez o nunca le ha oído balbucear o emitir sonidos guturales.",
         "is_critical": False, "order": 15},
        {"age_group": "05-06", "code": "05-06_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta sostener objetos con las manos durante al menos 10 segundos?",
         "is_critical": True, "order": 16},
        {"age_group": "05-06", "code": "05-06_ALE_6", "question_type": "ALARM", "area": None,
         "text": "Cuando está acostado y usted lo toma de las manos, ¿no hace esfuerzo para sentarse?",
         "is_critical": True, "order": 17},
        {"age_group": "05-06", "code": "05-06_ALE_7", "question_type": "ALARM", "area": None,
         "text": "Cuando está boca arriba, ¿se le dificulta girar su cuerpo hacia los lados?",
         "is_critical": True, "order": 18},
        {"age_group": "05-06", "code": "05-06_ALE_8", "question_type": "ALARM", "area": None,
         "text": "¿Considera que el desarrollo de su niño es inadecuado?",
         "is_critical": False, "order": 19},

        # ==================== GRUPO 07-09 (7-9 meses) ====================
        # Motriz Gruesa
        {"age_group": "07-09", "code": "07-09_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Al sentar a su bebé en el suelo, ¿permanece sentado aunque sea apoyándose en sus manos?",
         "is_critical": True, "order": 1},
        {"age_group": "07-09", "code": "07-09_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando su bebé quiere ir de un lado a otro y se encuentra boca arriba, ¿se voltea para quedar boca abajo y arrastrarse sobre su estómago?",
         "is_critical": True, "order": 2},
        
        # Motriz Fina
        {"age_group": "07-09", "code": "07-09_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "Cuando quiere agarrar las cosas, ¿utiliza sus dedos como si fueran un rastrillo?",
         "is_critical": True, "order": 3},
        {"age_group": "07-09", "code": "07-09_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Le gusta golpear objetos contra la mesa o el suelo?",
         "is_critical": False, "order": 4},
        
        # Lenguaje
        {"age_group": "07-09", "code": "07-09_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Puede hacer dos sonidos iguales como \"ba-ba\", \"da-da\", \"ta-ta\"?",
         "is_critical": False, "order": 5},
        {"age_group": "07-09", "code": "07-09_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Hace gestos para decir lo que quiere?",
         "is_critical": False, "order": 6},
        
        # Social
        {"age_group": "07-09", "code": "07-09_S_1", "question_type": "AREA", "area": "social",
         "text": "Cuando está con otras personas conocidas, ¿reacciona ante sus expresiones y parece contento?",
         "is_critical": False, "order": 7},
        {"age_group": "07-09", "code": "07-09_S_2", "question_type": "AREA", "area": "social",
         "text": "Cuando le da de beber líquidos, ¿lo ayuda a detener el vaso o la taza?",
         "is_critical": False, "order": 8},
        
        # Exploración Neurológica
        {"age_group": "07-09", "code": "07-09_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 9},
        {"age_group": "07-09", "code": "07-09_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 10},
        {"age_group": "07-09", "code": "07-09_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 11},
        
        # Señales de Alarma
        {"age_group": "07-09", "code": "07-09_ALE_1", "question_type": "ALARM", "area": None,
         "text": "¿Persiste el reflejo de Moro?",
         "is_critical": True, "order": 12},
        {"age_group": "07-09", "code": "07-09_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿Se encuentra ausente el reflejo de paracaídas?",
         "is_critical": True, "order": 13},
        {"age_group": "07-09", "code": "07-09_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta mantener un objeto en cada mano?",
         "is_critical": True, "order": 14},
        {"age_group": "07-09", "code": "07-09_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta seguir con la mirada un objeto que se cayó?",
         "is_critical": True, "order": 15},
        {"age_group": "07-09", "code": "07-09_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿Es indiferente a los objetos de su entorno?",
         "is_critical": True, "order": 16},
        {"age_group": "07-09", "code": "07-09_ALE_6", "question_type": "ALARM", "area": None,
         "text": "¿Considera que el desarrollo de su niño es inadecuado?",
         "is_critical": False, "order": 17},

        # ==================== GRUPO 10-12 (10-12 meses) ====================
        # Motriz Gruesa
        {"age_group": "10-12", "code": "10-12_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando su bebé se desplaza de un lado a otro, ¿utiliza sus manos y rodillas?",
         "is_critical": True, "order": 1},
        {"age_group": "10-12", "code": "10-12_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede su bebé caminar agarrado de los muebles?",
         "is_critical": True, "order": 2},
        
        # Motriz Fina
        {"age_group": "10-12", "code": "10-12_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede sujetar un objeto pequeño con los dedos y mantenerlo en el centro de la mano?",
         "is_critical": True, "order": 3},
        {"age_group": "10-12", "code": "10-12_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Sabe aplaudir?",
         "is_critical": False, "order": 4},
        
        # Lenguaje
        {"age_group": "10-12", "code": "10-12_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "Cuando su bebé está jugando en una actividad que lo tiene entretenido y usted le dice \"no, no\", ¿deja de hacerla?",
         "is_critical": True, "order": 5},
        {"age_group": "10-12", "code": "10-12_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Dice papá o mamá?",
         "is_critical": False, "order": 6},
        
        # Social
        {"age_group": "10-12", "code": "10-12_S_1", "question_type": "AREA", "area": "social",
         "text": "¿Empieza a comer por sí solo con los dedos?",
         "is_critical": False, "order": 7},
        {"age_group": "10-12", "code": "10-12_S_2", "question_type": "AREA", "area": "social",
         "text": "Cuando lo viste, ¿le ayuda terminando de meter el brazo por la manga?",
         "is_critical": False, "order": 8},
        
        # Exploración Neurológica
        {"age_group": "10-12", "code": "10-12_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 9},
        {"age_group": "10-12", "code": "10-12_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 10},
        {"age_group": "10-12", "code": "10-12_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 11},
        
        # Señales de Alarma
        {"age_group": "10-12", "code": "10-12_ALE_1", "question_type": "ALARM", "area": None,
         "text": "¿Necesita apoyarse en sus manos para permanecer sentado?",
         "is_critical": True, "order": 12},
        {"age_group": "10-12", "code": "10-12_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta comunicarse, ya sea balbuceando o con gestos? Por ejemplo: señalar lo que desea, mover la mano para saludar, hacer señas, jalar para llamar la atención.",
         "is_critical": False, "order": 13},
        {"age_group": "10-12", "code": "10-12_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta desplazarse o gatear?",
         "is_critical": True, "order": 14},
        {"age_group": "10-12", "code": "10-12_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿Es indiferente a los objetos de su entorno?",
         "is_critical": True, "order": 15},
        {"age_group": "10-12", "code": "10-12_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿Rara vez lo ha visto jugar?",
         "is_critical": False, "order": 16},
        {"age_group": "10-12", "code": "10-12_ALE_6", "question_type": "ALARM", "area": None,
         "text": "¿Considera que el desarrollo de su niño es inadecuado?",
         "is_critical": False, "order": 17},

        # ==================== GRUPO 13-15 (13-15 meses) ====================
        # Motriz Gruesa
        {"age_group": "13-15", "code": "13-15_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Camina solo?",
         "is_critical": True, "order": 1},
        {"age_group": "13-15", "code": "13-15_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando su niño está sentado, ¿puede pararse solo?",
         "is_critical": True, "order": 2},
        {"age_group": "13-15", "code": "13-15_MG_3", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede su niño agacharse para agarrar un objeto del suelo y volver a ponerse de pie sin apoyarse en algo?",
         "is_critical": True, "order": 3},
        
        # Motriz Fina
        {"age_group": "13-15", "code": "13-15_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Le gusta tirar o aventar juguetes u otros objetos al suelo?",
         "is_critical": False, "order": 4},
        {"age_group": "13-15", "code": "13-15_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Le gusta sacar y meter cosas de las bolsas, cajas o botes?",
         "is_critical": True, "order": 5},
        {"age_group": "13-15", "code": "13-15_MF_3", "question_type": "AREA", "area": "motriz_fina",
         "text": "Sin apoyar la mano o el brazo en la mesa, ¿puede tomar una bolita de papel utilizando las yemas de los dedos?",
         "is_critical": True, "order": 6},
        
        # Lenguaje
        {"age_group": "13-15", "code": "13-15_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Puede señalar su zapato o alguna parte del cuerpo?",
         "is_critical": True, "order": 7},
        {"age_group": "13-15", "code": "13-15_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Puede decir otra palabra además de papá y mamá?",
         "is_critical": False, "order": 8},
        {"age_group": "13-15", "code": "13-15_L_3", "question_type": "AREA", "area": "lenguaje",
         "text": "Cuando quiere algo, ¿se lo comunica con gestos y sonidos?",
         "is_critical": False, "order": 9},
        
        # Social
        {"age_group": "13-15", "code": "13-15_S_1", "question_type": "AREA", "area": "social",
         "text": "¿Come solo, sin que alguien le ayude?",
         "is_critical": False, "order": 10},
        {"age_group": "13-15", "code": "13-15_S_2", "question_type": "AREA", "area": "social",
         "text": "¿Le gusta abrazar o besar a sus papás?",
         "is_critical": False, "order": 11},
        {"age_group": "13-15", "code": "13-15_S_3", "question_type": "AREA", "area": "social",
         "text": "¿Obedece órdenes sencillas como: \"ven\", \"dámelo\", \"trae tu pelota\", etc.?",
         "is_critical": True, "order": 12},
        
        # Exploración Neurológica
        {"age_group": "13-15", "code": "13-15_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 13},
        {"age_group": "13-15", "code": "13-15_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 14},
        {"age_group": "13-15", "code": "13-15_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 15},
        
        # Señales de Alarma
        {"age_group": "13-15", "code": "13-15_ALE_1", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta desplazarse solo o gatear?",
         "is_critical": True, "order": 16},
        {"age_group": "13-15", "code": "13-15_ALE_2", "question_type": "ALARM", "area": None,
         "text": "Cuando colocas de pie a tu niño en una superficie plana, ¿no logra mantenerse parado aunque lo sujetes del tronco?",
         "is_critical": True, "order": 17},
        {"age_group": "13-15", "code": "13-15_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta comunicarse de forma verbal?",
         "is_critical": False, "order": 18},
        {"age_group": "13-15", "code": "13-15_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿Aún balbucea y no se expresa con palabras?",
         "is_critical": False, "order": 19},
        {"age_group": "13-15", "code": "13-15_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿Considera que el desarrollo de su niño es inadecuado?",
         "is_critical": False, "order": 20},

        # ==================== GRUPO 16-18 (16-18 meses) ====================
        # Motriz Gruesa
        {"age_group": "16-18", "code": "16-18_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede su niño sentarse solo en una silla pequeña?",
         "is_critical": False, "order": 1},
        {"age_group": "16-18", "code": "16-18_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede su niño patear una pelota?",
         "is_critical": True, "order": 2},
        {"age_group": "16-18", "code": "16-18_MG_3", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Corre aunque sea de forma torpe?",
         "is_critical": True, "order": 3},
        
        # Motriz Fina
        {"age_group": "16-18", "code": "16-18_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Sabe colocar cubos uno encima del otro?",
         "is_critical": True, "order": 4},
        {"age_group": "16-18", "code": "16-18_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede meter bolitas de papel en un frasco de plástico que tenga la boca chica?",
         "is_critical": True, "order": 5},
        {"age_group": "16-18", "code": "16-18_MF_3", "question_type": "AREA", "area": "motriz_fina",
         "text": "Si usted le da un pedazo de papel y un lápiz o crayón, ¿utiliza la punta para tratar de dibujar?",
         "is_critical": True, "order": 6},
        
        # Lenguaje
        {"age_group": "16-18", "code": "16-18_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Sabe decir cuatro palabras además de \"mamá\" y \"papá\"?",
         "is_critical": False, "order": 7},
        {"age_group": "16-18", "code": "16-18_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Puede señalar 2 o 3 partes de su cuerpo?",
         "is_critical": True, "order": 8},
        {"age_group": "16-18", "code": "16-18_L_3", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Sabe el nombre de algunos objetos?",
         "is_critical": True, "order": 9},
        
        # Social
        {"age_group": "16-18", "code": "16-18_S_1", "question_type": "AREA", "area": "social",
         "text": "¿Utiliza la cuchara para comer?",
         "is_critical": False, "order": 10},
        {"age_group": "16-18", "code": "16-18_S_2", "question_type": "AREA", "area": "social",
         "text": "Cuando va a desvestir a su niño, ¿le ayuda quitándose parte de su ropa, como los zapatos o huaraches?",
         "is_critical": False, "order": 11},
        {"age_group": "16-18", "code": "16-18_S_3", "question_type": "AREA", "area": "social",
         "text": "A su hijo, ¿le gusta imitarlo en tareas de la casa como barrer o sacudir?",
         "is_critical": False, "order": 12},
        
        # Exploración Neurológica
        {"age_group": "16-18", "code": "16-18_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 13},
        {"age_group": "16-18", "code": "16-18_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 14},
        {"age_group": "16-18", "code": "16-18_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 15},
        
        # Señales de Alarma
        {"age_group": "16-18", "code": "16-18_ALE_1", "question_type": "ALARM", "area": None,
         "text": "¿Se comunica únicamente con balbuceo, gritos o ruidos aislados?",
         "is_critical": False, "order": 16},
        {"age_group": "16-18", "code": "16-18_ALE_2", "question_type": "ALARM", "area": None,
         "text": "Para desplazarse, ¿solamente gatea o se arrastra?",
         "is_critical": True, "order": 17},
        {"age_group": "16-18", "code": "16-18_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Muestra conductas repetitivas o estereotipadas, por ejemplo: balancearse sin parar en su silla o golpearse la cabeza con las manos?",
         "is_critical": False, "order": 18},
        {"age_group": "16-18", "code": "16-18_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿La madre, padre o cuidador primario reporta que el niño ha experimentado una pérdida importante y constante de las habilidades que en algún momento tuvo?",
         "is_critical": False, "order": 19},
        {"age_group": "16-18", "code": "16-18_ALE_5", "question_type": "ALARM", "area": None,
         "text": "Cuando le preguntan dónde está una persona conocida, ¿es incapaz de señalarla?",
         "is_critical": True, "order": 20},
        {"age_group": "16-18", "code": "16-18_ALE_6", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta seguir órdenes sencillas, como: \"trae la pelota\"?",
         "is_critical": True, "order": 21},
        {"age_group": "16-18", "code": "16-18_ALE_7", "question_type": "ALARM", "area": None,
         "text": "¿Se enoja mucho y tiene dificultad para calmarse, comparado con otros niños de su edad?",
         "is_critical": False, "order": 22},

        # ==================== GRUPO 19-24 (19-24 meses) ====================
        # Motriz Gruesa
        {"age_group": "19-24", "code": "19-24_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede su niño subirse solo a los muebles?",
         "is_critical": False, "order": 1},
        {"age_group": "19-24", "code": "19-24_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Corre su niño sin caerse?",
         "is_critical": True, "order": 2},
        {"age_group": "19-24", "code": "19-24_MG_3", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Patea la pelota sin perder el equilibrio?",
         "is_critical": True, "order": 3},
        
        # Motriz Fina
        {"age_group": "19-24", "code": "19-24_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Intenta abrir un frasco de plástico girando la tapa rosca con la mano?",
         "is_critical": True, "order": 4},
        {"age_group": "19-24", "code": "19-24_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede desenvolver un juguete que esté envuelto en papel celofán?",
         "is_critical": True, "order": 5},
        {"age_group": "19-24", "code": "19-24_MF_3", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede comer ayudándose de una cuchara sin tirar la comida?",
         "is_critical": False, "order": 6},
        
        # Lenguaje
        {"age_group": "19-24", "code": "19-24_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Dice frases de dos palabras?",
         "is_critical": False, "order": 7},
        {"age_group": "19-24", "code": "19-24_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Sabe decir ocho o más palabras además de \"mamá\" y \"papá\"?",
         "is_critical": False, "order": 8},
        {"age_group": "19-24", "code": "19-24_L_3", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Obedece órdenes sencillas?",
         "is_critical": True, "order": 9},
        
        # Social
        {"age_group": "19-24", "code": "19-24_S_1", "question_type": "AREA", "area": "social",
         "text": "¿Trata de hacer las cosas solo y se molesta cuando no lo dejan?",
         "is_critical": False, "order": 10},
        {"age_group": "19-24", "code": "19-24_S_2", "question_type": "AREA", "area": "social",
         "text": "¿Avisa cuando ha ensuciado el pañal?",
         "is_critical": False, "order": 11},
        {"age_group": "19-24", "code": "19-24_S_3", "question_type": "AREA", "area": "social",
         "text": "¿Le pide ayuda cuando quiere algo que no alcanza?",
         "is_critical": False, "order": 12},
        
        # Exploración Neurológica
        {"age_group": "19-24", "code": "19-24_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 13},
        {"age_group": "19-24", "code": "19-24_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 14},
        {"age_group": "19-24", "code": "19-24_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 15},
        
        # Señales de Alarma
        {"age_group": "19-24", "code": "19-24_ALE_1", "question_type": "ALARM", "area": None,
         "text": "Cuando camina, ¿presenta una forma inmadura de hacerlo, primero apoya los dedos y luego el talón o después de varios meses sólo apoya las puntas de los pies?",
         "is_critical": True, "order": 16},
        {"age_group": "19-24", "code": "19-24_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿La madre, padre o cuidador primario reporta que el niño ha experimentado una pérdida importante y constante de las habilidades que en algún momento tuvo?",
         "is_critical": False, "order": 17},
        {"age_group": "19-24", "code": "19-24_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Tiene dificultad para seguir instrucciones sencillas, como \"dame tu zapato\"?",
         "is_critical": True, "order": 18},
        {"age_group": "19-24", "code": "19-24_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta mucho relacionarse con personas que no le son familiares?",
         "is_critical": False, "order": 19},
        {"age_group": "19-24", "code": "19-24_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿Muestra indiferencia excesiva al entorno, parece no interesarle nada de lo que sucede a su alrededor?",
         "is_critical": False, "order": 20},

        # ==================== GRUPO 25-30 (25-30 meses) ====================
        # Motriz Gruesa
        {"age_group": "25-30", "code": "25-30_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando su niño brinca, ¿levanta los dos pies del suelo a la vez?",
         "is_critical": True, "order": 1},
        {"age_group": "25-30", "code": "25-30_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede subir o bajar al menos dos escalones con ayuda?",
         "is_critical": False, "order": 2},
        {"age_group": "25-30", "code": "25-30_MG_3", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede su niño pararse sobre un solo pie?",
         "is_critical": True, "order": 3},
        
        # Motriz Fina
        {"age_group": "25-30", "code": "25-30_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Abre un frasco de plástico solo?",
         "is_critical": True, "order": 4},
        {"age_group": "25-30", "code": "25-30_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Lanza una pelota con la mano?",
         "is_critical": True, "order": 5},
        {"age_group": "25-30", "code": "25-30_MF_3", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Hace hileras con 4 cubos?",
         "is_critical": True, "order": 6},
        
        # Lenguaje
        {"age_group": "25-30", "code": "25-30_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Sabe decir su nombre?",
         "is_critical": True, "order": 7},
        {"age_group": "25-30", "code": "25-30_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Utiliza palabras como \"yo\", \"mío\", \"él\", \"ella\", \"tú\"?",
         "is_critical": False, "order": 8},
        {"age_group": "25-30", "code": "25-30_L_3", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Usa oraciones de 3 palabras, por ejemplo: \"quiero mi pelota\", \"dame mi leche\"?",
         "is_critical": False, "order": 9},
        
        # Social
        {"age_group": "25-30", "code": "25-30_S_1", "question_type": "AREA", "area": "social",
         "text": "¿Le ayuda a guardar las cosas de la casa en su lugar?",
         "is_critical": False, "order": 10},
        {"age_group": "25-30", "code": "25-30_S_2", "question_type": "AREA", "area": "social",
         "text": "¿Juega a simular cosas que vió?",
         "is_critical": False, "order": 11},
        {"age_group": "25-30", "code": "25-30_S_3", "question_type": "AREA", "area": "social",
         "text": "¿Se lava solo las manos y la cara?",
         "is_critical": False, "order": 12},
        
        # Exploración Neurológica
        {"age_group": "25-30", "code": "25-30_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 13},
        {"age_group": "25-30", "code": "25-30_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 14},
        {"age_group": "25-30", "code": "25-30_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 15},
        
        # Señales de Alarma
        {"age_group": "25-30", "code": "25-30_ALE_1", "question_type": "ALARM", "area": None,
         "text": "¿Muestra indiferencia excesiva al entorno?",
         "is_critical": False, "order": 16},
        {"age_group": "25-30", "code": "25-30_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿La madre, padre o cuidador primario reporta que el niño ha experimentado una pérdida importante y constante de las habilidades que en algún momento tuvo?",
         "is_critical": False, "order": 17},
        {"age_group": "25-30", "code": "25-30_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta mucho relacionarse con personas que no le son familiares?",
         "is_critical": False, "order": 18},
        {"age_group": "25-30", "code": "25-30_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿Se frustra mucho cuando se le dificulta hacer algo y deja de hacerlo o se pone a llorar?",
         "is_critical": False, "order": 19},

        # ==================== GRUPO 31-36 (31-36 meses) ====================
        # Motriz Gruesa
        {"age_group": "31-36", "code": "31-36_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede su niño agacharse fácilmente hacia adelante sin caerse?",
         "is_critical": True, "order": 1},
        {"age_group": "31-36", "code": "31-36_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede su niño caminar sobre la punta de sus pies?",
         "is_critical": True, "order": 2},
        {"age_group": "31-36", "code": "31-36_MG_3", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede caminar hacia atrás?",
         "is_critical": True, "order": 3},
        
        # Motriz Fina
        {"age_group": "31-36", "code": "31-36_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede abrochar un botón de una prenda de vestir?",
         "is_critical": False, "order": 4},
        {"age_group": "31-36", "code": "31-36_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede levantar una bola pequeña de papel del suelo tomándola con los dedos índice y pulgar?",
         "is_critical": True, "order": 5},
        {"age_group": "31-36", "code": "31-36_MF_3", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Imita trazos verticales y horizontales?",
         "is_critical": True, "order": 6},
        
        # Lenguaje
        {"age_group": "31-36", "code": "31-36_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Sabe decir su edad?",
         "is_critical": True, "order": 7},
        {"age_group": "31-36", "code": "31-36_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "Cuando está con personas que no conoce, ¿éstas entienden la mayoría de las palabras que dice?",
         "is_critical": False, "order": 8},
        {"age_group": "31-36", "code": "31-36_L_3", "question_type": "AREA", "area": "lenguaje",
         "text": "Cuando habla, ¿utiliza el plural de las palabras: \"perros\", \"juguetes\", \"niños\", etc.?",
         "is_critical": True, "order": 9},
        
        # Social
        {"age_group": "31-36", "code": "31-36_S_1", "question_type": "AREA", "area": "social",
         "text": "¿Juega con otros niños?",
         "is_critical": False, "order": 10},
        {"age_group": "31-36", "code": "31-36_S_2", "question_type": "AREA", "area": "social",
         "text": "¿Entiende la diferencia entre \"mío\" y \"tuyo\"?",
         "is_critical": False, "order": 11},
        {"age_group": "31-36", "code": "31-36_S_3", "question_type": "AREA", "area": "social",
         "text": "¿Se separa fácilmente de sus padres?",
         "is_critical": False, "order": 12},
        
        # Conocimiento
        {"age_group": "31-36", "code": "31-36_C_1", "question_type": "AREA", "area": "conocimiento",
         "text": "¿Sabe decir si es niño o niña?",
         "is_critical": True, "order": 13},
        {"age_group": "31-36", "code": "31-36_C_2", "question_type": "AREA", "area": "conocimiento",
         "text": "¿Dice frases como \"tengo sueño\", \"me quiero ir a dormir\"?",
         "is_critical": False, "order": 14},
        {"age_group": "31-36", "code": "31-36_C_3", "question_type": "AREA", "area": "conocimiento",
         "text": "¿Hace preguntas como: \"¿quién?\", \"¿cuándo?\", \"¿dónde?\", \"¿por qué?\"?",
         "is_critical": False, "order": 15},
        
        # Exploración Neurológica
        {"age_group": "31-36", "code": "31-36_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 16},
        {"age_group": "31-36", "code": "31-36_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 17},
        {"age_group": "31-36", "code": "31-36_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 18},
        
        # Señales de Alarma
        {"age_group": "31-36", "code": "31-36_ALE_1", "question_type": "ALARM", "area": None,
         "text": "¿Babea constantemente o habla de manera poco entendible?",
         "is_critical": False, "order": 19},
        {"age_group": "31-36", "code": "31-36_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿Se comunica con palabras aisladas es decir, no forma oraciones como \"mamá quiero leche\", y sólo dice \"leche\"?",
         "is_critical": False, "order": 20},
        {"age_group": "31-36", "code": "31-36_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Se cae frecuentemente y le cuesta trabajo subir o bajar escaleras?",
         "is_critical": False, "order": 21},
        {"age_group": "31-36", "code": "31-36_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿La madre, padre o cuidador primario reporta que el niño ha experimentado una pérdida importante y constante de las habilidades que en algún momento tuvo?",
         "is_critical": False, "order": 22},
        {"age_group": "31-36", "code": "31-36_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿Le cuesta trabajo manipular objetos pequeños como: bolas pequeñas de papel?",
         "is_critical": True, "order": 23},
        {"age_group": "31-36", "code": "31-36_ALE_6", "question_type": "ALARM", "area": None,
         "text": "¿Le cuesta trabajo entender órdenes sencillas como: \"ve con tu mamá\"?",
         "is_critical": True, "order": 24},
        {"age_group": "31-36", "code": "31-36_ALE_7", "question_type": "ALARM", "area": None,
         "text": "Cuando alguien le habla, ¿evita el contacto visual?",
         "is_critical": True, "order": 25},
        {"age_group": "31-36", "code": "31-36_ALE_8", "question_type": "ALARM", "area": None,
         "text": "¿Le cuesta mucho trabajo separarse de su mamá o de la persona que lo cuida y cuando se aleja de él se pone a llorar?",
         "is_critical": False, "order": 26},
        {"age_group": "31-36", "code": "31-36_ALE_9", "question_type": "ALARM", "area": None,
         "text": "¿Usa sus juguetes de forma inusual, es decir, en vez de rodar sus carritos o jugar con sus peluches, sólo los ordena por tamaño, color o forma?",
         "is_critical": False, "order": 27},

        # ==================== GRUPO 37-48 (37-48 meses) ====================
        # Motriz Gruesa
        {"age_group": "37-48", "code": "37-48_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "Cuando le avientan a su niño una pelota grande, ¿puede cacharla?",
         "is_critical": True, "order": 2},
        {"age_group": "37-48", "code": "37-48_MG_3", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Sube y baja las escaleras sin apoyarse de la pared o del barandal?",
         "is_critical": True, "order": 3},
        
        # Motriz Fina
        {"age_group": "37-48", "code": "37-48_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede meter una agujeta o cordón por los agujeros de una cuenta o de un zapato?",
         "is_critical": True, "order": 4},
        {"age_group": "37-48", "code": "37-48_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede dibujar una persona con 2 o más partes del cuerpo: ojos, naríz, boca, pelo, tronco, brazos, piernas, etc.?",
         "is_critical": True, "order": 5},
        {"age_group": "37-48", "code": "37-48_MF_3", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede dibujar un círculo o una cruz?",
         "is_critical": True, "order": 6},
        
        # Lenguaje
        {"age_group": "37-48", "code": "37-48_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Le dice lo que quiere con palabras?",
         "is_critical": False, "order": 7},
        {"age_group": "37-48", "code": "37-48_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Puede platicarle algo de lo que hizo ayer?",
         "is_critical": True, "order": 8},
        {"age_group": "37-48", "code": "37-48_L_3", "question_type": "AREA", "area": "lenguaje",
         "text": "Frecuentemente pregunta \"¿por qué?\"",
         "is_critical": False, "order": 9},
        
        # Social
        {"age_group": "37-48", "code": "37-48_S_1", "question_type": "AREA", "area": "social",
         "text": "¿Puede vestirse y desvestirse solo?",
         "is_critical": False, "order": 10},
        {"age_group": "37-48", "code": "37-48_S_2", "question_type": "AREA", "area": "social",
         "text": "¿Puede ir al baño solo?",
         "is_critical": False, "order": 11},
        {"age_group": "37-48", "code": "37-48_S_3", "question_type": "AREA", "area": "social",
         "text": "¿Juega con otros niños al papá, a la mamá, al doctor, policías y ladrones o a algún otro personaje?",
         "is_critical": False, "order": 12},
        
        # Conocimiento
        {"age_group": "37-48", "code": "37-48_C_1", "question_type": "AREA", "area": "conocimiento",
         "text": "¿Conoce el nombre de cuatro colores?",
         "is_critical": True, "order": 13},
        {"age_group": "37-48", "code": "37-48_C_2", "question_type": "AREA", "area": "conocimiento",
         "text": "¿Puede decir los nombres de dos o más números?",
         "is_critical": False, "order": 14},
        {"age_group": "37-48", "code": "37-48_C_3", "question_type": "AREA", "area": "conocimiento",
         "text": "¿Puede contarle una parte del cuento que le hayan contado o leído previamente?",
         "is_critical": False, "order": 15},
        
        # Exploración Neurológica
        {"age_group": "37-48", "code": "37-48_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 16},
        {"age_group": "37-48", "code": "37-48_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 17},
        {"age_group": "37-48", "code": "37-48_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 18},
        
        # Señales de Alarma
        {"age_group": "37-48", "code": "37-48_ALE_1", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta copiar un círculo en una hoja de papel?",
         "is_critical": True, "order": 19},
        {"age_group": "37-48", "code": "37-48_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿Solamente dice frases de 2 palabras?",
         "is_critical": False, "order": 20},
        {"age_group": "37-48", "code": "37-48_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿La madre, padre o cuidador primario reporta que el niño ha experimentado una pérdida importante y constante de las habilidades que en algún momento tuvo?",
         "is_critical": False, "order": 21},
        {"age_group": "37-48", "code": "37-48_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿Le cuesta trabajo tomar un lápiz o un crayón con los dedos índice, pulgar y medio?",
         "is_critical": True, "order": 22},
        {"age_group": "37-48", "code": "37-48_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿Es muy apegado a los padres y llora cuando se alejan, y es más notorio que en los otros niños de su edad?",
         "is_critical": False, "order": 23},
        {"age_group": "37-48", "code": "37-48_ALE_6", "question_type": "ALARM", "area": None,
         "text": "Cuando está con otros niños, ¿los ignora y prefiere jugar solo?",
         "is_critical": False, "order": 24},

        # ==================== GRUPO 49-59 (49-59 meses) ====================
        # Motriz Gruesa
        {"age_group": "49-59", "code": "49-59_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Sabe su niño darse marometas?",
         "is_critical": False, "order": 1},
        {"age_group": "49-59", "code": "49-59_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede su niño brincar hacia adelante cayendo con los pies juntos?",
         "is_critical": True, "order": 2},
        {"age_group": "49-59", "code": "49-59_MG_3", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede su niño brincar con un sólo pie hacia adelante tres veces cayendo con el mismo pie?",
         "is_critical": True, "order": 3},
        
        # Motriz Fina
        {"age_group": "49-59", "code": "49-59_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede dibujar un cuadrado?",
         "is_critical": True, "order": 4},
        {"age_group": "49-59", "code": "49-59_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Sabe escribir 2 o más letras?",
         "is_critical": True, "order": 5},
        {"age_group": "49-59", "code": "49-59_MF_3", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede dibujar una persona con 4 o más partes del cuerpo: ojos, naríz, boca, pelo, tronco, brazos, piernas, etc.?",
         "is_critical": True, "order": 6},
        
        # Lenguaje
        {"age_group": "49-59", "code": "49-59_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Sabe usar el tiempo futuro?",
         "is_critical": True, "order": 7},
        {"age_group": "49-59", "code": "49-59_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Puede contar cuentos?",
         "is_critical": True, "order": 8},
        {"age_group": "49-59", "code": "49-59_L_3", "question_type": "AREA", "area": "lenguaje",
         "text": "Cuando algo le gusta mucho, ¿dice: \"dame más\"?",
         "is_critical": False, "order": 9},
        
        # Social
        {"age_group": "49-59", "code": "49-59_S_1", "question_type": "AREA", "area": "social",
         "text": "¿Puede decir el nombre de dos de sus amigos?",
         "is_critical": False, "order": 10},
        {"age_group": "49-59", "code": "49-59_S_2", "question_type": "AREA", "area": "social",
         "text": "¿Le gusta jugar al papá o a la mamá o actuar como otra persona de la familia?",
         "is_critical": False, "order": 11},
        {"age_group": "49-59", "code": "49-59_S_3", "question_type": "AREA", "area": "social",
         "text": "¿Se puede bañar solo?",
         "is_critical": False, "order": 12},
        
        # Conocimiento
        {"age_group": "49-59", "code": "49-59_C_1", "question_type": "AREA", "area": "conocimiento",
         "text": "¿Puede decir el nombre correcto de cuatro colores y los puede reconocer?",
         "is_critical": True, "order": 13},
        {"age_group": "49-59", "code": "49-59_C_2", "question_type": "AREA", "area": "conocimiento",
         "text": "¿Puede contar correctamente hasta diez?",
         "is_critical": True, "order": 14},
        {"age_group": "49-59", "code": "49-59_C_3", "question_type": "AREA", "area": "conocimiento",
         "text": "Cuando habla, ¿utiliza las palabras \"ayer\", \"hoy\" y \"mañana\"?",
         "is_critical": False, "order": 15},
        
        # Exploración Neurológica
        {"age_group": "49-59", "code": "49-59_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 16},
        {"age_group": "49-59", "code": "49-59_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 17},
        {"age_group": "49-59", "code": "49-59_NEURO_3", "question_type": "NEURO", "area": None,
         "text": "¿Presenta perímetro cefálico por arriba o por debajo de 2 desviaciones estándar para su edad?",
         "is_critical": True, "order": 18},
        
        # Señales de Alarma
        {"age_group": "49-59", "code": "49-59_ALE_1", "question_type": "ALARM", "area": None,
         "text": "Cuando está con otros niños, ¿los ignora y prefiere jugar solo?",
         "is_critical": False, "order": 19},
        {"age_group": "49-59", "code": "49-59_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿La madre, padre o cuidador primario reporta que el niño ha experimentado una pérdida importante y constante de las habilidades que en algún momento tuvo?",
         "is_critical": False, "order": 20},
        {"age_group": "49-59", "code": "49-59_ALE_3", "question_type": "ALARM", "area": None,
         "text": "Cuando habla, ¿usa incorrectamente los plurales y el tiempo pasado?, por ejemplo no dice palabras como: \"tazas\", \"cucharas\", \"ayer vino mi abuelita\"",
         "is_critical": True, "order": 21},
        {"age_group": "49-59", "code": "49-59_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿Aún se le dificulta desvestirse solo, por ejemplo: abotonar, amarrar agujetas, ponerse o quitarse una playera, etc.?",
         "is_critical": False, "order": 22},
        {"age_group": "49-59", "code": "49-59_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿Se distrae fácilmente y le cuesta mucho trabajo concentrarse en alguna actividad por más de 5 minutos?",
         "is_critical": False, "order": 23},
        {"age_group": "49-59", "code": "49-59_ALE_6", "question_type": "ALARM", "area": None,
         "text": "¿Actúa tímidamente o se muestra demasiado asustado?",
         "is_critical": False, "order": 24},
        {"age_group": "49-59", "code": "49-59_ALE_7", "question_type": "ALARM", "area": None,
         "text": "Cuando sus padres se separan de él ¿llora y protesta mucho?",
         "is_critical": False, "order": 25},
        {"age_group": "49-59", "code": "49-59_ALE_8", "question_type": "ALARM", "area": None,
         "text": "¿Se le dificulta decir correctamente su nombre y apellido?",
         "is_critical": True, "order": 26},
        {"age_group": "49-59", "code": "49-59_ALE_9", "question_type": "ALARM", "area": None,
         "text": "¿Expresa de manera pobre sus emociones?",
         "is_critical": False, "order": 27},
        {"age_group": "49-59", "code": "49-59_ALE_10", "question_type": "ALARM", "area": None,
         "text": "¿Constantemente se lo ve inactivo y poco interesado en lo que pasa a su alrededor?",
         "is_critical": False, "order": 28},

        # ==================== GRUPO 60-71 (60-71 meses) ====================
        # Motriz Gruesa
        {"age_group": "60-71", "code": "60-71_MG_1", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede brincar con un solo pie hacia adelante siete veces cayendo con el mismo pie?",
         "is_critical": True, "order": 1},
        {"age_group": "60-71", "code": "60-71_MG_2", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Puede brincar hacia atrás con los pies juntos?",
         "is_critical": True, "order": 2},
        {"age_group": "60-71", "code": "60-71_MG_3", "question_type": "AREA", "area": "motriz_gruesa",
         "text": "¿Camina siguiendo una línea recta, juntando el talón de un pie con la punta del otro pie, por lo menos 5 pasos?",
         "is_critical": True, "order": 3},
        
        # Motriz Fina
        {"age_group": "60-71", "code": "60-71_MF_1", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede dibujar un triángulo copiándolo?",
         "is_critical": True, "order": 4},
        {"age_group": "60-71", "code": "60-71_MF_2", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede tocar la punta de su dedo pulgar con la punta de cada dedo de la misma mano consecutivamente?",
         "is_critical": True, "order": 5},
        {"age_group": "60-71", "code": "60-71_MF_3", "question_type": "AREA", "area": "motriz_fina",
         "text": "¿Puede cortar el papel con tijeras de punta redonda siguiendo una línea recta, teniendo 1 cm de margen de error?",
         "is_critical": True, "order": 6},
        
        # Lenguaje
        {"age_group": "60-71", "code": "60-71_L_1", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Habla con suficiente claridad para que otros lo entiendan?",
         "is_critical": True, "order": 7},
        {"age_group": "60-71", "code": "60-71_L_2", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Comunica sus emociones diciendo palabras como: \"feliz\", \"triste\", \"enojado\"? (si recibes regalos, ¿cómo te sientes?).",
         "is_critical": True, "order": 8},
        {"age_group": "60-71", "code": "60-71_L_3", "question_type": "AREA", "area": "lenguaje",
         "text": "¿Puede seguir ordenes verbales de tres pasos, por ejemplo: \"aplaude, dame el lápiz y ponte de pie\"?",
         "is_critical": True, "order": 9},
        
        # Social
        {"age_group": "60-71", "code": "60-71_S_1", "question_type": "AREA", "area": "social",
         "text": "¿La mayoría de las veces comparte fácilmente sus cosas con otros niños?",
         "is_critical": False, "order": 10},
        {"age_group": "60-71", "code": "60-71_S_2", "question_type": "AREA", "area": "social",
         "text": "¿Le gusta ir a la escuela?",
         "is_critical": False, "order": 11},
        {"age_group": "60-71", "code": "60-71_S_3", "question_type": "AREA", "area": "social",
         "text": "¿Espera su turno con facilidad cuando interactúa con sus compañeros, maestros o cuidadores primarios?",
         "is_critical": False, "order": 12},
        
        # Conocimiento
        {"age_group": "60-71", "code": "60-71_C_1", "question_type": "AREA", "area": "conocimiento",
         "text": "Cuando le pides que escriba 2 números o 2 letras, ¿lo hace?",
         "is_critical": True, "order": 13},
        {"age_group": "60-71", "code": "60-71_C_2", "question_type": "AREA", "area": "conocimiento",
         "text": "¿Puede completar oraciones con la palabra que significa lo opuesto? Por ejemplo: \"el conejo es rápido, la tortuga es...\"",
         "is_critical": True, "order": 14},
        {"age_group": "60-71", "code": "60-71_C_3", "question_type": "AREA", "area": "conocimiento",
         "text": "¿Identifica el valor de dos o más monedas o billetes?",
         "is_critical": True, "order": 15},
        
        # Exploración Neurológica
        {"age_group": "60-71", "code": "60-71_NEURO_1", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración en la movilidad de alguna parte del cuerpo?",
         "is_critical": True, "order": 16},
        {"age_group": "60-71", "code": "60-71_NEURO_2", "question_type": "NEURO", "area": None,
         "text": "¿Presenta alteración o asimetría en la movilidad de ojos o expresión facial?",
         "is_critical": True, "order": 17},
        
        # Señales de Alarma
        {"age_group": "60-71", "code": "60-71_ALE_1", "question_type": "ALARM", "area": None,
         "text": "¿Presenta dolores de cabeza persistentes, visión borrosa o mareo?",
         "is_critical": False, "order": 18},
        {"age_group": "60-71", "code": "60-71_ALE_2", "question_type": "ALARM", "area": None,
         "text": "¿Presenta dificultad para cepillarse los dientes, lavarse y secarse las manos o desvestirse sin ayuda?",
         "is_critical": False, "order": 19},
        {"age_group": "60-71", "code": "60-71_ALE_3", "question_type": "ALARM", "area": None,
         "text": "¿Durante más de tres días a la semana el niño presenta miedo, agresión, timidez o tristeza en mayor intensidad que los niños de su edad?",
         "is_critical": False, "order": 20},
        {"age_group": "60-71", "code": "60-71_ALE_4", "question_type": "ALARM", "area": None,
         "text": "¿El niño necesita acercarse mucho a los objetos que le llaman la atención o inclina la cabeza para verlos?",
         "is_critical": False, "order": 21},
        {"age_group": "60-71", "code": "60-71_ALE_5", "question_type": "ALARM", "area": None,
         "text": "¿El niño se cae frecuentemente al correr?",
         "is_critical": False, "order": 22},
        {"age_group": "60-71", "code": "60-71_ALE_6", "question_type": "ALARM", "area": None,
         "text": "¿Se distrae fácilmente y le cuesta mucho trabajo concentrarse en alguna actividad por más de cinco minutos?",
         "is_critical": False, "order": 23},
        {"age_group": "60-71", "code": "60-71_ALE_7", "question_type": "ALARM", "area": None,
         "text": "¿El niño se orina en la cama por las noches?",
         "is_critical": False, "order": 24},
    ]
    
    # Eliminar preguntas existentes (opcional, comentar si no se desea)
    print("Eliminando preguntas existentes...")
    EDIQuestion.objects.all().delete()
    
    # Crear las preguntas
    print("Creando preguntas EDI...")
    created_count = 0
    for q_data in questions_data:
        try:
            EDIQuestion.objects.create(**q_data)
            created_count += 1
        except Exception as e:
            print(f"Error creando pregunta {q_data['code']}: {e}")
    
    print(f"\n✅ Se crearon {created_count} preguntas EDI exitosamente")
    print(f"Total de grupos de edad: 15")
    print("Grupos: 01, 02, 03, 04, 05-06, 07-09, 10-12, 13-15, 16-18, 19-24, 25-30, 31-36, 37-48, 49-59, 60-71")

# Ejecutar la función
create_edi_questions()
