# Generated by Django 6.0 on 2025-12-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_evaluation_age_group_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
