# Generated by Django 6.0 on 2025-12-15 02:29

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=20, verbose_name='Grupo de edad')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código único')),
                ('question_type', models.CharField(choices=[('AREA', 'Área de Desarrollo'), ('NEURO', 'Exploración Neurológica'), ('ALARM', 'Señal de Alarma'), ('BIO', 'Factor de Riesgo Biológico')], max_length=10)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField(verbose_name='Texto de la pregunta')),
                ('is_critical', models.BooleanField(default=False, verbose_name='¿Es crítica? (**)')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Pregunta EDI',
                'verbose_name_plural': 'Preguntas EDI',
                'ordering': ['age_group', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question_code'], 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Evaluación EDI', 'verbose_name_plural': 'Evaluaciones EDI'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='score_total',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='status',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(
                choices=[('AREA', 'Área de Desarrollo'), ('NEURO', 'Exploración Neurológica'), ('ALARM', 'Señal de Alarma'), ('BIO', 'Factor de Riesgo Biológico')],
                default='final',
                max_length=10,
                verbose_name='Tipo de pregunta'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='area',
            field=models.CharField(blank=True, help_text='motriz_gruesa, motriz_fina, lenguaje, social, conocimiento', max_length=50, null=True, verbose_name='Área de desarrollo'),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='from_previous_group',
            field=models.BooleanField(default=False, verbose_name='¿Del grupo anterior?'),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Preguntas marcadas con ** en el documento', verbose_name='¿Es crítica? (**)'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='age_in_months',
            field=models.IntegerField(default=0, help_text='Edad corregida si aplica', verbose_name='Edad en meses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='alarm_signals_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de señales de alarma'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='alarm_signals_status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10, null=True, verbose_name='Estado de señales de alarma'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='applied_previous_group',
            field=models.BooleanField(default=False, verbose_name='¿Se aplicaron preguntas del grupo anterior?'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='biological_risk_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de factores de riesgo'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='biological_risk_status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10, null=True, verbose_name='Estado de factores de riesgo'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='conocimiento_status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10, null=True, verbose_name='Conocimiento'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='diagnosis',
            field=models.CharField(
                choices=[('NORMAL', 'Desarrollo Normal'), ('DELAY', 'Rezago en el desarrollo'), ('RISK', 'Riesgo de retraso en el desarrollo')],
                default='NORMAL',
                max_length=20,
                verbose_name='Diagnóstico'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='final_status',
            field=models.CharField(
                choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')],
                default='GREEN',
                max_length=10,
                verbose_name='Estado final'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='lenguaje_status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10, null=True, verbose_name='Lenguaje'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='motriz_fina_status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10, null=True, verbose_name='Motriz Fina'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='motriz_gruesa_status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10, null=True, verbose_name='Motriz Gruesa'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='neurological_red_flags',
            field=models.IntegerField(default=0, verbose_name='Señales rojas neurológicas'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='neurological_status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10, null=True, verbose_name='Exploración Neurológica'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='notes',
            field=models.TextField(blank=True, help_text='Comentarios adicionales del evaluador', verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='previous_group_result',
            field=models.CharField(blank=True, choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10, null=True, verbose_name='Resultado del grupo anterior'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='social_status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10, null=True, verbose_name='Social'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='used_corrected_age',
            field=models.BooleanField(default=False, verbose_name='¿Se usó edad corregida?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gestational_weeks',
            field=models.IntegerField(blank=True, help_text='Dejar vacío si nació a término (≥37 semanas)', null=True, verbose_name='Semanas de gestación'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_premature',
            field=models.BooleanField(default=False, verbose_name='¿Es prematuro?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Form.evaluation', verbose_name='Evaluación'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_code',
            field=models.CharField(help_text='Ej: 01_MG_1, 02_MF_2, 03_NEURO_1', max_length=50, verbose_name='Código de pregunta'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.BooleanField(verbose_name='Respuesta (Sí/No)'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='age_group',
            field=models.CharField(help_text='Ej: 01, 02, 05-06, 07-09', max_length=20, verbose_name='Grupo de edad EDI'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Form.patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='document_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cédula/ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro/No especifica')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
