# Generated by Django 6.0 on 2025-12-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0005_evaluation_alert_signals_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='document_id',
            field=models.CharField(default='null', max_length=30, unique=True, verbose_name='Cédula / Historia clínica'),
            preserve_default=False,
        ),
    ]
