# Generated by Django 5.2.9 on 2026-01-06 05:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_alter_patient_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('min_months', models.PositiveSmallIntegerField()),
                ('max_months', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAreaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('motriz_gruesa', 'Motriz Gruesa'), ('motriz_fina', 'Motriz Fina'), ('lenguaje', 'Lenguaje'), ('social', 'Social'), ('conocimiento', 'Conocimiento')], max_length=30)),
                ('yes_count', models.PositiveSmallIntegerField(default=0)),
                ('total_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationDomainResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('NEURO', 'Exploración Neurológica'), ('ALARM', 'Señal de Alarma'), ('ALERT', 'Señal de Alerta'), ('BIO', 'Factor de Riesgo Biológico')], max_length=10)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('red_flags', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_previous_group', models.BooleanField(default=False)),
                ('previous_group_result', models.CharField(blank=True, choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10, null=True)),
                ('diagnosis', models.CharField(choices=[('NORMAL', 'Desarrollo Normal'), ('DELAY', 'Rezago en el desarrollo'), ('RISK', 'Riesgo de retraso en el desarrollo')], max_length=20)),
                ('final_status', models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('trace', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('domain', models.CharField(choices=[('AREA', 'Área de Desarrollo'), ('NEURO', 'Exploración Neurológica'), ('ALARM', 'Señal de Alarma'), ('ALERT', 'Señal de Alerta'), ('BIO', 'Factor de Riesgo Biológico')], max_length=10)),
                ('area', models.CharField(blank=True, choices=[('motriz_gruesa', 'Motriz Gruesa'), ('motriz_fina', 'Motriz Fina'), ('lenguaje', 'Lenguaje'), ('social', 'Social'), ('conocimiento', 'Conocimiento')], max_length=30, null=True)),
                ('text', models.TextField()),
                ('is_critical', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['age_band__code', 'display_order'],
            },
        ),
        migrations.DeleteModel(
            name='EDIQuestion',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='alarm_signals_count',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='alarm_signals_status',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='alert_signals_count',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='alert_signals_status',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='applied_previous_group',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='biological_risk_count',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='biological_risk_status',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='conocimiento_status',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='final_status',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='lenguaje_status',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='motriz_fina_status',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='motriz_gruesa_status',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='neurological_red_flags',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='neurological_status',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='previous_group_result',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='social_status',
        ),
        migrations.AddField(
            model_name='answer',
            name='value_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='answer',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Form.evaluation'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='from_previous_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='age_in_months',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Form.patient'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='used_corrected_age',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='document_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gestational_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_premature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro/No especifica')], max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['document_id'], name='Form_patien_documen_30885b_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='Form_patien_full_na_1585c0_idx'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='age_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='Form.ageband'),
        ),
        migrations.AddField(
            model_name='evaluationarearesult',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_results', to='Form.evaluation'),
        ),
        migrations.AddField(
            model_name='evaluationdomainresult',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_results', to='Form.evaluation'),
        ),
        migrations.AddField(
            model_name='evaluationsummary',
            name='evaluation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='Form.evaluation'),
        ),
        migrations.AddField(
            model_name='instrumentversion',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='Form.instrument'),
        ),
        migrations.AddField(
            model_name='ageband',
            name='instrument_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='age_bands', to='Form.instrumentversion'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='instrument_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='Form.instrumentversion'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['patient', 'created_at'], name='Form_evalua_patient_ec80e7_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['instrument_version', 'age_band'], name='Form_evalua_instrum_efb43a_idx'),
        ),
        migrations.AddField(
            model_name='question',
            name='age_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='Form.ageband'),
        ),
        migrations.AddField(
            model_name='question',
            name='instrument_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='Form.instrumentversion'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='Form.question'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['evaluation', 'question'], name='Form_answer_evaluat_ae8d44_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'from_previous_group'], name='Form_answer_questio_e7e54a_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('evaluation', 'question'), name='uq_answer_per_question_not_null'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_type',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_critical',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_code',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
        migrations.AddIndex(
            model_name='evaluationarearesult',
            index=models.Index(fields=['area', 'status'], name='Form_evalua_area_8e5a99_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationarearesult',
            constraint=models.UniqueConstraint(fields=('evaluation', 'area'), name='uq_area_result_per_eval'),
        ),
        migrations.AddIndex(
            model_name='evaluationdomainresult',
            index=models.Index(fields=['domain', 'status'], name='Form_evalua_domain_9ee6ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationdomainresult',
            constraint=models.UniqueConstraint(fields=('evaluation', 'domain'), name='uq_domain_result_per_eval'),
        ),
        migrations.AddIndex(
            model_name='evaluationsummary',
            index=models.Index(fields=['diagnosis', 'final_status'], name='Form_evalua_diagnos_be974d_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumentversion',
            index=models.Index(fields=['instrument', 'is_active'], name='Form_instru_instrum_73dd36_idx'),
        ),
        migrations.AddConstraint(
            model_name='instrumentversion',
            constraint=models.UniqueConstraint(fields=('instrument', 'version'), name='uq_instrument_version'),
        ),
        migrations.AddIndex(
            model_name='ageband',
            index=models.Index(fields=['instrument_version', 'min_months', 'max_months'], name='Form_ageban_instrum_8bc33e_idx'),
        ),
        migrations.AddConstraint(
            model_name='ageband',
            constraint=models.UniqueConstraint(fields=('instrument_version', 'code'), name='uq_ageband_code_per_version'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['instrument_version', 'age_band', 'display_order'], name='Form_questi_instrum_75d12c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['domain', 'area'], name='Form_questi_domain_f743e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('instrument_version', 'code'), name='uq_question_code_per_version'),
        ),
    ]
